name: CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: pravaha-api
      run: pip install -r requirements.txt

    - name: Run tests
      working-directory: pravaha-api
      run: python -m unittest discover -s tests -p "test_*.py"

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker to Artifact Registry
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    - name: Build and push Docker image
      run: |
        docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pravaha-repo/pravaha-api ./pravaha-api
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pravaha-repo/pravaha-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy pravaha-api \
          --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pravaha-repo/pravaha-api \
          --region asia-south1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080
          --set-secrets OPENAI_API_KEY=projects/pravaha-project/secrets/OPENAI_API_KEY:latest

